### ISSUE TITLE
Upgrade to new python plugin method

### ISSUE THREAD

**Issue by deefrawley** [Ma-ve/Flow.Launcher.Plugin.FancyEmoji#1]
Hey Ma-ve,

Flow python plugins can use embedded python now which saves the users having to manually install dependencies. If you have a look at this plugin you can see that main.py adds a local lib folder to the system path and CI script installs the python dependencies there

https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert

You could also use the CI script to unzip the images.zip your plugin uses so everything is ready to go for the user when the install finishes.

**Comment by Ma-ve** [comment]
Hey @deefrawley! Thanks for bringing this to my attention: I've only just recently seen that you had opened an issue, apologies for the late response. I've tried implementing that. That's fine - however, what do you mean when you say 'embedded Python'?

When installing GenConvert, I still get prompted to set up a Python directory from FlowLauncher itself. Should that be the case, still?

**Comment by deefrawley** [comment]
Hi @Ma-ve. When a user downloads a python plugin for the first time, Flow will ask if they would like to download and install python and install as part of Flow, or if the user would like to use an existing install on their PC - that's what I meant by 'embedded'.
