### ISSUE TITLE
minor: update repository description

### ISSUE THREAD

**Issue by TheBestPessimist** [Ma-ve/Flow.Launcher.Plugin.FancyEmoji#8]
Right now it sais it's for Wox launcher:
![image](https://user-images.githubusercontent.com/4482210/212470026-bb7ae1fd-a084-46ab-8378-a0cf3c5cb92d.png)

**Comment by Ma-ve** [comment]
Hey! I'm incredibly late to the party. Where are you seeing this? Please open a new issue if this persists.

**Comment by TheBestPessimist** [comment]
not closed. it's on the front page, in the description

![image](https://github.com/Ma-ve/Flow.Launcher.Plugin.FancyEmoji/assets/4482210/41715294-1db4-49f8-b2f4-0bb9ecaadd8a)

**Comment by Ma-ve** [comment]
> @TheBestPessimist not closed. it's on the front page, in the description
> 


Ah, good catch! Totally missed that. Updated! Thanks!
